version: '3'

services:
  web:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
  server:
    container_name: elysia-server
    build:
      context: .
      dockerfile: ./apps/elysia-server/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
  h5:
    container_name: h5-app
    build:
      context: .
      dockerfile: ./apps/h5-app/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 5080:80
      - 5443:443
  admin:
    container_name: admin-platform
    build:
      context: .
      dockerfile: ./apps/admin-platform/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8000:80
      - 8443:443
