version: '3'

services:
  web:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
  server:
    container_name: api-server
    build:
      context: .
      dockerfile: ./apps/api-server/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 5000:5000
