version: '3'

services:
  web:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
  server:
    container_name: fastify-server
    build:
      context: .
      dockerfile: ./apps/fastify-server/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
