# 项目 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-deployment
  namespace: $PROJECT_NAME
  labels:
    app: $APP_NAME
  annotations:
    kubesphere.io/creator: $KUBESPHERE_USER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $REGISTRY/$APP_NAME/$IMAGE
          ports:
            - name: http-80
              containerPort: 80
              protocol: HTTP

---
# 项目 Service
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-service
  namespace: $PROJECT_NAME
  annotations:
    kubesphere.io/creator: $KUBESPHERE_USER
spec:
  selector:
    app: $APP_NAME
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

---
# 项目 Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $APP_NAME-ingress
  namespace: $PROJECT_NAME
  annotations:
    kubesphere.io/creator: $KUBESPHERE_USER
spec:
  # tls:
  #   - hosts:
  #       - $DOMAIN_NAME
  #     secretName: service-tls
  rules:
    - host: $DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: $APP_NAME-service
                port:
                  number: 80
